//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("appdynamics-agent", Namespace="", IsNullable=false)]
public partial class AppDynamicsAgentType {
    
    private ControllerType controllerField;
    
    private MachineAgentType machineagentField;
    
    private AppAgentsType appagentsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ControllerType controller {
        get {
            return this.controllerField;
        }
        set {
            this.controllerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("machine-agent", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MachineAgentType machineagent {
        get {
            return this.machineagentField;
        }
        set {
            this.machineagentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("app-agents", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AppAgentsType appagents {
        get {
            return this.appagentsField;
        }
        set {
            this.appagentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ControllerType {
    
    private ControllerTypeApplication applicationField;
    
    private ControllerTypeApplication1[] applicationsField;
    
    private ControllerTypeAccount accountField;
    
    private ControllerTypeProxy proxyField;
    
    private string hostField;
    
    private int portField;
    
    private bool portFieldSpecified;
    
    private bool sslField;
    
    private bool sslFieldSpecified;
    
    private bool high_availabilityField;
    
    private bool high_availabilityFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ControllerTypeApplication application {
        get {
            return this.applicationField;
        }
        set {
            this.applicationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("application", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ControllerTypeApplication1[] applications {
        get {
            return this.applicationsField;
        }
        set {
            this.applicationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ControllerTypeAccount account {
        get {
            return this.accountField;
        }
        set {
            this.accountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ControllerTypeProxy proxy {
        get {
            return this.proxyField;
        }
        set {
            this.proxyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string host {
        get {
            return this.hostField;
        }
        set {
            this.hostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool portSpecified {
        get {
            return this.portFieldSpecified;
        }
        set {
            this.portFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool ssl {
        get {
            return this.sslField;
        }
        set {
            this.sslField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sslSpecified {
        get {
            return this.sslFieldSpecified;
        }
        set {
            this.sslFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool high_availability {
        get {
            return this.high_availabilityField;
        }
        set {
            this.high_availabilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool high_availabilitySpecified {
        get {
            return this.high_availabilityFieldSpecified;
        }
        set {
            this.high_availabilityFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ControllerTypeApplication {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AppAgentType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AppAgentWithProfilerType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AppAgentBaseType {
    
    private AppAgentBaseTypeEum eumField;
    
    private AppAgentBaseTypeInterceptor[] interceptorsField;
    
    private AppAgentBaseTypeProperties propertiesField;
    
    private AppAgentBaseTypeIpc ipcField;
    
    private AppAgentBaseTypeAppagentconfiguration appagentconfigurationField;
    
    private bool enabledField;
    
    private string controllerapplicationField;
    
    public AppAgentBaseType() {
        this.enabledField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AppAgentBaseTypeEum eum {
        get {
            return this.eumField;
        }
        set {
            this.eumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("interceptor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public AppAgentBaseTypeInterceptor[] interceptors {
        get {
            return this.interceptorsField;
        }
        set {
            this.interceptorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AppAgentBaseTypeProperties properties {
        get {
            return this.propertiesField;
        }
        set {
            this.propertiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AppAgentBaseTypeIpc ipc {
        get {
            return this.ipcField;
        }
        set {
            this.ipcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("app-agent-configuration", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AppAgentBaseTypeAppagentconfiguration appagentconfiguration {
        get {
            return this.appagentconfigurationField;
        }
        set {
            this.appagentconfigurationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("controller-application")]
    public string controllerapplication {
        get {
            return this.controllerapplicationField;
        }
        set {
            this.controllerapplicationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AppAgentBaseTypeEum {
    
    private bool enabledField;
    
    public AppAgentBaseTypeEum() {
        this.enabledField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AppAgentBaseTypeInterceptor {
    
    private string nameField;
    
    private bool enabledField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AppAgentBaseTypeProperties {
    
    private bool thread_array_use_tlsField;
    
    private bool thread_array_use_tlsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool thread_array_use_tls {
        get {
            return this.thread_array_use_tlsField;
        }
        set {
            this.thread_array_use_tlsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool thread_array_use_tlsSpecified {
        get {
            return this.thread_array_use_tlsFieldSpecified;
        }
        set {
            this.thread_array_use_tlsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AppAgentBaseTypeIpc {
    
    private uint connecttimeoutField;
    
    private bool connecttimeoutFieldSpecified;
    
    private int responsetimeoutdefaultField;
    
    private bool responsetimeoutdefaultFieldSpecified;
    
    private int responsetimeoutperformancecountersField;
    
    private bool responsetimeoutperformancecountersFieldSpecified;
    
    private int responsetimeoutinstancecountsField;
    
    private bool responsetimeoutinstancecountsFieldSpecified;
    
    private int responsetimeoutlogpullField;
    
    private bool responsetimeoutlogpullFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("connect-timeout")]
    public uint connecttimeout {
        get {
            return this.connecttimeoutField;
        }
        set {
            this.connecttimeoutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool connecttimeoutSpecified {
        get {
            return this.connecttimeoutFieldSpecified;
        }
        set {
            this.connecttimeoutFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("response-timeout-default")]
    public int responsetimeoutdefault {
        get {
            return this.responsetimeoutdefaultField;
        }
        set {
            this.responsetimeoutdefaultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool responsetimeoutdefaultSpecified {
        get {
            return this.responsetimeoutdefaultFieldSpecified;
        }
        set {
            this.responsetimeoutdefaultFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("response-timeout-performance-counters")]
    public int responsetimeoutperformancecounters {
        get {
            return this.responsetimeoutperformancecountersField;
        }
        set {
            this.responsetimeoutperformancecountersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool responsetimeoutperformancecountersSpecified {
        get {
            return this.responsetimeoutperformancecountersFieldSpecified;
        }
        set {
            this.responsetimeoutperformancecountersFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("response-timeout-instance-counts")]
    public int responsetimeoutinstancecounts {
        get {
            return this.responsetimeoutinstancecountsField;
        }
        set {
            this.responsetimeoutinstancecountsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool responsetimeoutinstancecountsSpecified {
        get {
            return this.responsetimeoutinstancecountsFieldSpecified;
        }
        set {
            this.responsetimeoutinstancecountsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("response-timeout-log-pull")]
    public int responsetimeoutlogpull {
        get {
            return this.responsetimeoutlogpullField;
        }
        set {
            this.responsetimeoutlogpullField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool responsetimeoutlogpullSpecified {
        get {
            return this.responsetimeoutlogpullFieldSpecified;
        }
        set {
            this.responsetimeoutlogpullFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AppAgentBaseTypeAppagentconfiguration {
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AppAgentWithProfilerType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AppAgentType : AppAgentBaseType {
    
    private AppAgentTypeTier tierField;
    
    private AppAgentTypeNode nodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AppAgentTypeTier tier {
        get {
            return this.tierField;
        }
        set {
            this.tierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AppAgentTypeNode node {
        get {
            return this.nodeField;
        }
        set {
            this.nodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AppAgentTypeTier {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AppAgentTypeNode {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AppAgentWithProfilerType : AppAgentType {
    
    private ProfilerType profilerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfilerType profiler {
        get {
            return this.profilerField;
        }
        set {
            this.profilerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ProfilerType {
    
    private ProfilerTypeCallgraph callgraphField;
    
    private ProfilerTypeTreatverificationexceptionmethods treatverificationexceptionmethodsField;
    
    private ProfilerTypeInstrumentdefaultdomain instrumentdefaultdomainField;
    
    private ProfilerTypeLegacyinstrumentationdecisions legacyinstrumentationdecisionsField;
    
    private ProfilerTypeFilter[] filtersField;
    
    private ProfilerTypeAssemblywhitelist assemblywhitelistField;
    
    private ProfilerTypeAdvancedperformance advancedperformanceField;
    
    private ProfilerTypeElt eltField;
    
    private bool enabledField;
    
    public ProfilerType() {
        this.enabledField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfilerTypeCallgraph callgraph {
        get {
            return this.callgraphField;
        }
        set {
            this.callgraphField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("treat-verification-exception-methods", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfilerTypeTreatverificationexceptionmethods treatverificationexceptionmethods {
        get {
            return this.treatverificationexceptionmethodsField;
        }
        set {
            this.treatverificationexceptionmethodsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("instrument-defaultdomain", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfilerTypeInstrumentdefaultdomain instrumentdefaultdomain {
        get {
            return this.instrumentdefaultdomainField;
        }
        set {
            this.instrumentdefaultdomainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("legacy-instrumentation-decisions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfilerTypeLegacyinstrumentationdecisions legacyinstrumentationdecisions {
        get {
            return this.legacyinstrumentationdecisionsField;
        }
        set {
            this.legacyinstrumentationdecisionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("filter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ProfilerTypeFilter[] filters {
        get {
            return this.filtersField;
        }
        set {
            this.filtersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("assembly-white-list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfilerTypeAssemblywhitelist assemblywhitelist {
        get {
            return this.assemblywhitelistField;
        }
        set {
            this.assemblywhitelistField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("advanced-performance", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfilerTypeAdvancedperformance advancedperformance {
        get {
            return this.advancedperformanceField;
        }
        set {
            this.advancedperformanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfilerTypeElt elt {
        get {
            return this.eltField;
        }
        set {
            this.eltField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfilerTypeCallgraph {
    
    private bool hooksField;
    
    private bool hooksFieldSpecified;
    
    private bool watchdogField;
    
    private bool watchdogFieldSpecified;
    
    private bool overridedssField;
    
    private bool overridedssFieldSpecified;
    
    private bool overridehooksField;
    
    private bool overridehooksFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool hooks {
        get {
            return this.hooksField;
        }
        set {
            this.hooksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool hooksSpecified {
        get {
            return this.hooksFieldSpecified;
        }
        set {
            this.hooksFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool watchdog {
        get {
            return this.watchdogField;
        }
        set {
            this.watchdogField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool watchdogSpecified {
        get {
            return this.watchdogFieldSpecified;
        }
        set {
            this.watchdogFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool overridedss {
        get {
            return this.overridedssField;
        }
        set {
            this.overridedssField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool overridedssSpecified {
        get {
            return this.overridedssFieldSpecified;
        }
        set {
            this.overridedssFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool overridehooks {
        get {
            return this.overridehooksField;
        }
        set {
            this.overridehooksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool overridehooksSpecified {
        get {
            return this.overridehooksFieldSpecified;
        }
        set {
            this.overridehooksFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfilerTypeTreatverificationexceptionmethods {
    
    private int valueField;
    
    private bool valueFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool valueSpecified {
        get {
            return this.valueFieldSpecified;
        }
        set {
            this.valueFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfilerTypeInstrumentdefaultdomain {
    
    private bool enabledField;
    
    private bool enabledFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool enabledSpecified {
        get {
            return this.enabledFieldSpecified;
        }
        set {
            this.enabledFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfilerTypeLegacyinstrumentationdecisions {
    
    private bool enabledField;
    
    private bool enabledFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool enabledSpecified {
        get {
            return this.enabledFieldSpecified;
        }
        set {
            this.enabledFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfilerTypeFilter {
    
    private string textField;
    
    private string filterontypeField;
    
    private string filtermatchtypeField;
    
    private bool includefunctionifruleappliesField;
    
    private bool includefunctionifruleappliesFieldSpecified;
    
    private bool explicitField;
    
    private bool explicitFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("filter-on-type")]
    public string filterontype {
        get {
            return this.filterontypeField;
        }
        set {
            this.filterontypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("filter-match-type")]
    public string filtermatchtype {
        get {
            return this.filtermatchtypeField;
        }
        set {
            this.filtermatchtypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("include-function-if-rule-applies")]
    public bool includefunctionifruleapplies {
        get {
            return this.includefunctionifruleappliesField;
        }
        set {
            this.includefunctionifruleappliesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool includefunctionifruleappliesSpecified {
        get {
            return this.includefunctionifruleappliesFieldSpecified;
        }
        set {
            this.includefunctionifruleappliesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool @explicit {
        get {
            return this.explicitField;
        }
        set {
            this.explicitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool explicitSpecified {
        get {
            return this.explicitFieldSpecified;
        }
        set {
            this.explicitFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfilerTypeAssemblywhitelist {
    
    private ProfilerTypeAssemblywhitelistAssembly[] assemblyField;
    
    private bool usedefaultField;
    
    public ProfilerTypeAssemblywhitelist() {
        this.usedefaultField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("assembly", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfilerTypeAssemblywhitelistAssembly[] assembly {
        get {
            return this.assemblyField;
        }
        set {
            this.assemblyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("use-default")]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool usedefault {
        get {
            return this.usedefaultField;
        }
        set {
            this.usedefaultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfilerTypeAssemblywhitelistAssembly {
    
    private string textField;
    
    private string filtermatchtypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("filter-match-type")]
    public string filtermatchtype {
        get {
            return this.filtermatchtypeField;
        }
        set {
            this.filtermatchtypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfilerTypeAdvancedperformance {
    
    private ProfilerTypeAdvancedperformanceAssembly[] assemblyField;
    
    private int optionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("assembly", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfilerTypeAdvancedperformanceAssembly[] assembly {
        get {
            return this.assemblyField;
        }
        set {
            this.assemblyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfilerTypeAdvancedperformanceAssembly {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfilerTypeElt {
    
    private ProfilerTypeEltRule[] rulesField;
    
    private bool enabledField;
    
    private string logpathField;
    
    private bool useinstrumentortriggersField;
    
    private int delayField;
    
    private int durationField;
    
    public ProfilerTypeElt() {
        this.enabledField = true;
        this.useinstrumentortriggersField = false;
        this.delayField = 0;
        this.durationField = 0;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("rule", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ProfilerTypeEltRule[] rules {
        get {
            return this.rulesField;
        }
        set {
            this.rulesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("log-path")]
    public string logpath {
        get {
            return this.logpathField;
        }
        set {
            this.logpathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("use-instrumentor-triggers")]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool useinstrumentortriggers {
        get {
            return this.useinstrumentortriggersField;
        }
        set {
            this.useinstrumentortriggersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int delay {
        get {
            return this.delayField;
        }
        set {
            this.delayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ProfilerTypeEltRule {
    
    private string matchtypeField;
    
    private string matchopField;
    
    private string ruletypeField;
    
    private string textField;
    
    public ProfilerTypeEltRule() {
        this.matchopField = "equals";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("match-type")]
    public string matchtype {
        get {
            return this.matchtypeField;
        }
        set {
            this.matchtypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("match-op")]
    [System.ComponentModel.DefaultValueAttribute("equals")]
    public string matchop {
        get {
            return this.matchopField;
        }
        set {
            this.matchopField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("rule-type")]
    public string ruletype {
        get {
            return this.ruletypeField;
        }
        set {
            this.ruletypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AppAgentsType {
    
    private AppAgentsTypeActivities activitiesField;
    
    private ProfilerType profilerField;
    
    private AppAgentsTypeIIS iISField;
    
    private AppAgentsTypeStandaloneapplications standaloneapplicationsField;
    
    private AppAgentsTypeWindowsservices windowsservicesField;
    
    private bool enabledField;
    
    private bool azureField;
    
    private bool azureFieldSpecified;
    
    private string azurerolenameField;
    
    private string azureroleinstanceidField;
    
    private string appendprocessindexField;
    
    public AppAgentsType() {
        this.enabledField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AppAgentsTypeActivities activities {
        get {
            return this.activitiesField;
        }
        set {
            this.activitiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfilerType profiler {
        get {
            return this.profilerField;
        }
        set {
            this.profilerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AppAgentsTypeIIS IIS {
        get {
            return this.iISField;
        }
        set {
            this.iISField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("standalone-applications", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AppAgentsTypeStandaloneapplications standaloneapplications {
        get {
            return this.standaloneapplicationsField;
        }
        set {
            this.standaloneapplicationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("windows-services", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AppAgentsTypeWindowsservices windowsservices {
        get {
            return this.windowsservicesField;
        }
        set {
            this.windowsservicesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool azure {
        get {
            return this.azureField;
        }
        set {
            this.azureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool azureSpecified {
        get {
            return this.azureFieldSpecified;
        }
        set {
            this.azureFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("azure-role-name")]
    public string azurerolename {
        get {
            return this.azurerolenameField;
        }
        set {
            this.azurerolenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("azure-role-instance-id")]
    public string azureroleinstanceid {
        get {
            return this.azureroleinstanceidField;
        }
        set {
            this.azureroleinstanceidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("append-process-index")]
    public string appendprocessindex {
        get {
            return this.appendprocessindexField;
        }
        set {
            this.appendprocessindexField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AppAgentsTypeActivities {
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AppAgentsTypeIIS {
    
    private AppAgentsTypeIISAutomatic automaticField;
    
    private AppAgentsTypeIISApplicationpool[] applicationpoolsField;
    
    private AppAgentsTypeIISApplication[] applicationsField;
    
    private AppAgentsTypeIISProfiler[] profilersField;
    
    private bool enabledField;
    
    private bool markwebgardennodeshistoricalField;
    
    private bool markwebgardennodeshistoricalFieldSpecified;
    
    public AppAgentsTypeIIS() {
        this.enabledField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AppAgentsTypeIISAutomatic automatic {
        get {
            return this.automaticField;
        }
        set {
            this.automaticField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("application-pools", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("application-pool", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public AppAgentsTypeIISApplicationpool[] applicationpools {
        get {
            return this.applicationpoolsField;
        }
        set {
            this.applicationpoolsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("application", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public AppAgentsTypeIISApplication[] applications {
        get {
            return this.applicationsField;
        }
        set {
            this.applicationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("profiler", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public AppAgentsTypeIISProfiler[] profilers {
        get {
            return this.profilersField;
        }
        set {
            this.profilersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("mark-webgarden-nodes-historical")]
    public bool markwebgardennodeshistorical {
        get {
            return this.markwebgardennodeshistoricalField;
        }
        set {
            this.markwebgardennodeshistoricalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool markwebgardennodeshistoricalSpecified {
        get {
            return this.markwebgardennodeshistoricalFieldSpecified;
        }
        set {
            this.markwebgardennodeshistoricalFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AppAgentsTypeIISAutomatic : AppAgentBaseType {
    
    private ProfilerType profilerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ProfilerType profiler {
        get {
            return this.profilerField;
        }
        set {
            this.profilerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AppAgentsTypeIISApplicationpool : AppAgentType {
    
    private string nameField;
    
    private string appdomainnameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("app-domain-name")]
    public string appdomainname {
        get {
            return this.appdomainnameField;
        }
        set {
            this.appdomainnameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AppAgentsTypeIISApplication : AppAgentType {
    
    private string pathField;
    
    private string siteField;
    
    private string portField;
    
    private string appdomainnameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string site {
        get {
            return this.siteField;
        }
        set {
            this.siteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("app-domain-name")]
    public string appdomainname {
        get {
            return this.appdomainnameField;
        }
        set {
            this.appdomainnameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AppAgentsTypeIISProfiler : ProfilerType {
    
    private string applicationpoolField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("application-pool")]
    public string applicationpool {
        get {
            return this.applicationpoolField;
        }
        set {
            this.applicationpoolField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AppAgentsTypeStandaloneapplications {
    
    private AppAgentsTypeStandaloneapplicationsStandaloneapplication[] standaloneapplicationField;
    
    private bool enabledField;
    
    public AppAgentsTypeStandaloneapplications() {
        this.enabledField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("standalone-application", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AppAgentsTypeStandaloneapplicationsStandaloneapplication[] standaloneapplication {
        get {
            return this.standaloneapplicationField;
        }
        set {
            this.standaloneapplicationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AppAgentsTypeStandaloneapplicationsStandaloneapplication : AppAgentWithProfilerType {
    
    private string executableField;
    
    private string appdomainnameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string executable {
        get {
            return this.executableField;
        }
        set {
            this.executableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("app-domain-name")]
    public string appdomainname {
        get {
            return this.appdomainnameField;
        }
        set {
            this.appdomainnameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AppAgentsTypeWindowsservices {
    
    private AppAgentsTypeWindowsservicesWindowsservice[] windowsserviceField;
    
    private bool enabledField;
    
    public AppAgentsTypeWindowsservices() {
        this.enabledField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("windows-service", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AppAgentsTypeWindowsservicesWindowsservice[] windowsservice {
        get {
            return this.windowsserviceField;
        }
        set {
            this.windowsserviceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AppAgentsTypeWindowsservicesWindowsservice : AppAgentWithProfilerType {
    
    private string nameField;
    
    private string appdomainnameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("app-domain-name")]
    public string appdomainname {
        get {
            return this.appdomainnameField;
        }
        set {
            this.appdomainnameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MachineAgentType {
    
    private MachineAgentTypeTier tierField;
    
    private MachineAgentTypeNode nodeField;
    
    private MachineAgentTypeInstrumentor[] instrumentationField;
    
    private MachineAgentTypePerfcounters perfcountersField;
    
    private MachineAgentTypeAssemblyblacklist assemblyblacklistField;
    
    private MachineAgentTypeHistoricalnodes historicalnodesField;
    
    private MachineAgentTypeMachinesnapshot machinesnapshotField;
    
    private MachineAgentTypeClrcrashreporting clrcrashreportingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MachineAgentTypeTier tier {
        get {
            return this.tierField;
        }
        set {
            this.tierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MachineAgentTypeNode node {
        get {
            return this.nodeField;
        }
        set {
            this.nodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("instrumentor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public MachineAgentTypeInstrumentor[] instrumentation {
        get {
            return this.instrumentationField;
        }
        set {
            this.instrumentationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("perf-counters", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MachineAgentTypePerfcounters perfcounters {
        get {
            return this.perfcountersField;
        }
        set {
            this.perfcountersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("assembly-black-list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MachineAgentTypeAssemblyblacklist assemblyblacklist {
        get {
            return this.assemblyblacklistField;
        }
        set {
            this.assemblyblacklistField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("historical-nodes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MachineAgentTypeHistoricalnodes historicalnodes {
        get {
            return this.historicalnodesField;
        }
        set {
            this.historicalnodesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("machine-snapshot", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MachineAgentTypeMachinesnapshot machinesnapshot {
        get {
            return this.machinesnapshotField;
        }
        set {
            this.machinesnapshotField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("clrcrash-reporting", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MachineAgentTypeClrcrashreporting clrcrashreporting {
        get {
            return this.clrcrashreportingField;
        }
        set {
            this.clrcrashreportingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MachineAgentTypeTier {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MachineAgentTypeNode {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MachineAgentTypeInstrumentor {
    
    private string nameField;
    
    private bool enabledField;
    
    private string argsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string args {
        get {
            return this.argsField;
        }
        set {
            this.argsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MachineAgentTypePerfcounters {
    
    private MachineAgentTypePerfcountersPerfcounter[] perfcounterField;
    
    private int cachetimeoutinsecsField;
    
    private bool cachetimeoutinsecsFieldSpecified;
    
    private int updateintervalinsecsField;
    
    private bool updateintervalinsecsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("perf-counter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MachineAgentTypePerfcountersPerfcounter[] perfcounter {
        get {
            return this.perfcounterField;
        }
        set {
            this.perfcounterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("cache-timeout-in-secs")]
    public int cachetimeoutinsecs {
        get {
            return this.cachetimeoutinsecsField;
        }
        set {
            this.cachetimeoutinsecsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cachetimeoutinsecsSpecified {
        get {
            return this.cachetimeoutinsecsFieldSpecified;
        }
        set {
            this.cachetimeoutinsecsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("update-interval-in-secs")]
    public int updateintervalinsecs {
        get {
            return this.updateintervalinsecsField;
        }
        set {
            this.updateintervalinsecsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool updateintervalinsecsSpecified {
        get {
            return this.updateintervalinsecsFieldSpecified;
        }
        set {
            this.updateintervalinsecsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MachineAgentTypePerfcountersPerfcounter {
    
    private string catField;
    
    private string nameField;
    
    private string instanceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cat {
        get {
            return this.catField;
        }
        set {
            this.catField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string instance {
        get {
            return this.instanceField;
        }
        set {
            this.instanceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MachineAgentTypeAssemblyblacklist {
    
    private int blacklistafterloadsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("blacklist-after-loads")]
    public int blacklistafterloads {
        get {
            return this.blacklistafterloadsField;
        }
        set {
            this.blacklistafterloadsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MachineAgentTypeHistoricalnodes {
    
    private int updateintervalinsecsField;
    
    private bool updateintervalinsecsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("update-interval-in-secs")]
    public int updateintervalinsecs {
        get {
            return this.updateintervalinsecsField;
        }
        set {
            this.updateintervalinsecsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool updateintervalinsecsSpecified {
        get {
            return this.updateintervalinsecsFieldSpecified;
        }
        set {
            this.updateintervalinsecsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MachineAgentTypeMachinesnapshot {
    
    private bool enabledField;
    
    private int windowsizeField;
    
    private bool windowsizeFieldSpecified;
    
    private int samplesperwindowField;
    
    private bool samplesperwindowFieldSpecified;
    
    private int violationsperwindowField;
    
    private bool violationsperwindowFieldSpecified;
    
    private int maxpercentcpuField;
    
    private bool maxpercentcpuFieldSpecified;
    
    private int maxpercentmemoryField;
    
    private bool maxpercentmemoryFieldSpecified;
    
    private int maxqueueitemageField;
    
    private bool maxqueueitemageFieldSpecified;
    
    private int periodiccollectionField;
    
    private bool periodiccollectionFieldSpecified;
    
    public MachineAgentTypeMachinesnapshot() {
        this.enabledField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("window-size")]
    public int windowsize {
        get {
            return this.windowsizeField;
        }
        set {
            this.windowsizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool windowsizeSpecified {
        get {
            return this.windowsizeFieldSpecified;
        }
        set {
            this.windowsizeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("samples-per-window")]
    public int samplesperwindow {
        get {
            return this.samplesperwindowField;
        }
        set {
            this.samplesperwindowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool samplesperwindowSpecified {
        get {
            return this.samplesperwindowFieldSpecified;
        }
        set {
            this.samplesperwindowFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("violations-per-window")]
    public int violationsperwindow {
        get {
            return this.violationsperwindowField;
        }
        set {
            this.violationsperwindowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool violationsperwindowSpecified {
        get {
            return this.violationsperwindowFieldSpecified;
        }
        set {
            this.violationsperwindowFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("max-percent-cpu")]
    public int maxpercentcpu {
        get {
            return this.maxpercentcpuField;
        }
        set {
            this.maxpercentcpuField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxpercentcpuSpecified {
        get {
            return this.maxpercentcpuFieldSpecified;
        }
        set {
            this.maxpercentcpuFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("max-percent-memory")]
    public int maxpercentmemory {
        get {
            return this.maxpercentmemoryField;
        }
        set {
            this.maxpercentmemoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxpercentmemorySpecified {
        get {
            return this.maxpercentmemoryFieldSpecified;
        }
        set {
            this.maxpercentmemoryFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("max-queue-item-age")]
    public int maxqueueitemage {
        get {
            return this.maxqueueitemageField;
        }
        set {
            this.maxqueueitemageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxqueueitemageSpecified {
        get {
            return this.maxqueueitemageFieldSpecified;
        }
        set {
            this.maxqueueitemageFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("periodic-collection")]
    public int periodiccollection {
        get {
            return this.periodiccollectionField;
        }
        set {
            this.periodiccollectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool periodiccollectionSpecified {
        get {
            return this.periodiccollectionFieldSpecified;
        }
        set {
            this.periodiccollectionFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MachineAgentTypeClrcrashreporting {
    
    private bool enabledField;
    
    public MachineAgentTypeClrcrashreporting() {
        this.enabledField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ControllerTypeApplication1 {
    
    private string nameField;
    
    private bool defaultField;
    
    public ControllerTypeApplication1() {
        this.defaultField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool @default {
        get {
            return this.defaultField;
        }
        set {
            this.defaultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ControllerTypeAccount {
    
    private string nameField;
    
    private string passwordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ControllerTypeProxy {
    
    private ControllerTypeProxyAuthentication authenticationField;
    
    private string hostField;
    
    private int portField;
    
    private bool enabledField;
    
    public ControllerTypeProxy() {
        this.enabledField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ControllerTypeProxyAuthentication authentication {
        get {
            return this.authenticationField;
        }
        set {
            this.authenticationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string host {
        get {
            return this.hostField;
        }
        set {
            this.hostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ControllerTypeProxyAuthentication {
    
    private bool enabledField;
    
    private string user_nameField;
    
    private string passwordField;
    
    private string domainField;
    
    public ControllerTypeProxyAuthentication() {
        this.enabledField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string user_name {
        get {
            return this.user_nameField;
        }
        set {
            this.user_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string domain {
        get {
            return this.domainField;
        }
        set {
            this.domainField = value;
        }
    }
}
